#
# ~/.bashrc
#


# If not running interactively, don't do anything
[ -z "$PS1" ] && return


if [ -z "$INPUTRC" -a ! -f "$HOME/.inputrc" ]; then
	INPUTRC=/etc/inputrc
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# check for vcprompt - https://github.com/djl/vcprompt
hash vcprompt &> /dev/null

if [ $? -eq 0 ];then
    # haz it
    PS1='\[\033[01;35m\]$(vcprompt) \[\033[00;32m\]$\[\033[00m\] '
else
    PS1=' \[\033[00;32m\]$\[\033[00m\] '
fi

# If this is an xterm set the title to user@host:dir
# otherwise add this info to the prompt
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;\w\a\]$PS1"
    ;;
*)
    PS1="\w$PS1"
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
fi

# Colorized ls
alias ls='ls --color=auto'

# Keep the color in less
alias less='less -R'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'
alias grepr='grep -r -I --color=auto'

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias ..='cd ..'

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

set -o vi
force_color_prompt='yes'

# Use git-completion if available
if [ -e "$HOME/.git-completion.bash" ]; then
    source "$HOME/.git-completion.bash"
fi;

[[ "$(uname)" == "Darwin" ]] && [[ -e "~/.osx_profile" ]] && source ~/.osx_profile

eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

export PATH="$HOME/bin:$PATH"

export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - bash)"

[[ -s "/home/gmflanagan/.gvm/scripts/gvm" ]] && source "/home/gmflanagan/.gvm/scripts/gvm"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
